export const CHANNELS = {
  RECORDING_START: 'recording:start',
  RECORDING_STOP: 'recording:stop',
  RECORDING_CANCEL: 'recording:cancel',
  RECORDING_AUDIO: 'recording:audio',
  RECORDING_ERROR: 'recording:error',
  OVERLAY_STATE: 'overlay:state',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET: 'settings:set',
  SETTINGS_GET_KEY_STATUS: 'settings:get-key-status',
  SETTINGS_GET_KEY: 'settings:get-key',
  SETTINGS_SET_KEY: 'settings:set-key',
  SETTINGS_CLEAR_KEY: 'settings:clear-key',
  HISTORY_GET_ALL: 'history:get-all',
  HISTORY_DELETE: 'history:delete',
  HISTORY_CLEAR: 'history:clear',
  HISTORY_EXPORT: 'history:export',
  CLIPBOARD_WRITE: 'clipboard:write',
  SHORTCUTS_PAUSE: 'shortcuts:pause',
  SHORTCUTS_RESUME: 'shortcuts:resume',
  SHORTCUTS_GET_STATUS: 'shortcuts:get-status',
  SYSTEM_GET_LOCALE: 'system:get-locale',
  SHELL_OPEN_PATH: 'shell:open-path',
  SHELL_OPEN_RECORDINGS_PATH: 'shell:open-recordings-path',
  RECORDINGS_GET_PATH: 'recordings:get-path',
  LOG_FORWARD: 'log:forward',
  LOG_WORKER: 'log:worker',
  UI_THEME_CHANGED: 'ui:theme-changed',
  HISTORY_ENTRY_ADDED: 'history:entry-added',
  UPDATE_STATUS: 'update:status',
  UPDATE_CHECK: 'update:check',
  UPDATE_INSTALL: 'update:install',
  UPDATE_GET_VERSION: 'update:get-version',
  UPDATE_GET_STATUS: 'update:get-status',
  SHELL_OPEN_EXTERNAL: 'shell:open-external',
  APP_GET_REPO_URL: 'app:get-repo-url',
  OVERLAY_RESET_POSITION: 'overlay:reset-position',
  OVERLAY_POSITION_CHANGED: 'overlay:position-changed',
  OVERLAY_SETTINGS_CHANGED: 'overlay:settings-changed',
  OVERLAY_PREVIEW: 'overlay:preview',
  LOG_GET_ALL: 'log:get-all',
  NAVIGATE: 'navigate',
  NAVIGATE_REQUEST: 'navigate-request'
} as const

export type Channel = (typeof CHANNELS)[keyof typeof CHANNELS]
